# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  polygon:
    image: polygon
    build:
      context: .
      dockerfile: Polygon.CMS/Dockerfile
    ports:
      - 5001